### ISSUE TITLE
Verbose option does not print the command when sudo is enabled

### ISSUE THREAD

**Issue by r2vq** [goliatone/arpscan#10]
**DESCRIPTION**
When calling the `scanner(cb, options)` function in verbose mode, the command won't print if sudo mode is enabled.

**STEPS TO REPRODUCE**
1. Set `options.verbose` to `true`.
1. Set `options.sudo` to `true`.
1. Invoke the `scanner(cb, options)` method.

**EXPECTED RESULTS**
- The command should print to the console like the following:

    ```
    sudo arp-scan -l -interface wlan0
    ```

**ACTUAL RESULTS**
- The command prints to the console only the word `sudo` followed by an empty space:

    ```
    sudo 
    ```

**Comment by goliatone** [comment]
@r2vq merged, thanks
