### ISSUE TITLE
make interfaces optional

### ISSUE THREAD

**Issue by drrobotnik** [goliatone/arpscan#12]
`arp-scan -l` is a valid command but as far as I can tell not possible with your node implementation. I tried setting the value to null but it wouldn't work. I was able to get the feature working the way I had wanted by removing line 47 in arpscanner.js.

https://github.com/goliatone/arpscan/blob/e8984984df8cd96dc1521eee663f6ce04d0e0131/lib/arpscanner.js#L47

Ideally this flag would be optional. I looked at the forks of your repo and this seems to be a common change.

**Comment by linge123** [comment]
hello， when i run this code , throw error  Uncaught Error: Cannot find module "child_process",how to solve it？
