### ISSUE TITLE
returns error in basic example

### ISSUE THREAD

**Issue by kujosHeist** [goliatone/arpscan#3]
When running the following example I get error 1 returned:

```
var arpscanner = require('arpscan');
arpscanner(onResult);

function onResult(err, data){
    if(err){
	console.log("Error number: "+ err);
    }else{
	console.log(data);
    }
  
}


```
ubuntu 12.04 32-bit
npm: 3.10.6
node: 4.5.0
arpscan: 0.1.0
arp-scan 1.8.1

I got the following warning when installing:

`npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

Thanks

**Comment by nagromc** [comment]
In order to perform an `arp-scan`, you need root privileges.

Either
- run

        $ # assuming your app is named index.js
        $ sudo node index.js

- or, for a more "industrial" and permission-safe fashion, add an `options` object to grant root permission **only** when `arp-scan` is invoked (as it is described in PR #2):

    ```javascript
    var arpscanner = require('arpscan');

    var options = {
        sudo: true
    }

    arpscanner(onResult, options);

    function onResult(err, data){
        if (err) {
            console.log("Error number: "+ err);
        } else {
            console.log(data);
        }
    }
    ```
You can add the user that will run the app with

         $ # do *NOT* `sudo vim /etc/sudoers.d/arpscan`. Seriously, don't do that. Otherwise, you could break your installation
         $ sudo visudo -f /etc/sudoers.d/arpscan
then adding the following line (where `foo` is the wanted user)

        foo ALL = (root) NOPASSWD: /usr/bin/arp-scan

You can ignore the warning message relative to `minimatch` during installation. It has nothing to do with the exit status `1`.

Maybe the documentation needs to be updated.

**Comment by kujosHeist** [comment]
Thanks for the quick response!

I used sudo when running the file and got the same result, not sure what's going wrong

Thanks

**Comment by nagromc** [comment]
Could you send the result of the following commands **as regular user**?

1. Find what is the `arp-scan` binary as regular user:

        $ whereis arp-scan

2. Find what is the `arp-scan` binary as regular user with elevated privileges:

        $ sudo whereis arp-scan

3. Check out the exit status of `arp-scan -l` executed as regular user:

        $ arp-scan -l > /dev/null; echo $?

4. Check out the exit status of `arp-scan -l` executed as regular user with elevated privileges:

        $ sudo arp-scan -l > /dev/null; echo $?

On my machine, I have the following result (executed as regular user):

1. 

        arp-scan: /usr/bin/arp-scan /usr/share/arp-scan /usr/share/man/man1/arp-scan.1.gz

2. 

        arp-scan: /usr/bin/arp-scan /usr/share/arp-scan /usr/share/man/man1/arp-scan.1.gz

3. 

        You need to be root, or arp-scan must be SUID root, to open a link-layer socket.
        link_open: Operation not permitted
        1

    We are interested in the last line and the text after `link_open`. Here, it is obvious that the current user is not allowed to run `arp-scan`

4. 

        0

Make sure you have the same results. If not, we'll investigate further.

**Comment by kujosHeist** [comment]
Hey sorry for delay, I updated to 16.04 and everything works fine, thanks!

**Comment by sebsonf** [comment]
Hey,

I just had the same problem when running the example code. Both, adding the sudo: true option and running sudo node app.js didn't change the behavior, I was still getting an error corresponding to the exit status 1. I was able to fix it using the command sudo chmod u+s /usr/bin/arp-scan setting it to be SUID root and then running the app without sudo privileges. Can you give any advice what is the recommended way? 

Thanks by the way for the great module, just the thing I was looking for!

**Comment by nagromc** [comment]
Is there any error message? Could you provide the output of [my previous message](https://github.com/goliatone/arpscan/issues/3#issuecomment-245633169)?

**Comment by sebsonf** [comment]
Both commands (1. & 2.): `arp-scan: /usr/bin/arp-scan /usr/bin/X11/arp-scan /usr/share/arp-scan /usr/share/man/man1/arp-scan.1.gz`

Both commands (3. & 4.): return exit status 0

Note however, I get this after I applied the command `sudo chmod u+s /usr/bin/arp-scan` yesterday. Got this command from another module description ([https://github.com/mikerodrigues/arp_scan](url)).

**Comment by nagromc** [comment]
Well, I'm not an expert and I cannot explain why `arp-scan` needs elevated privileges, but I think you should not change the `setuid` attribute of softwares in `/usr/bin`. I recommend to restore the `setuid`:

    $ sudo chmod u-s /usr/bin/arp-scan

Instead, use the [method](https://github.com/goliatone/arpscan/pull/2#issue-85077517) described in issue #2, or in [my previous comment](https://github.com/goliatone/arpscan/issues/3#issuecomment-242343981). Then, we'll try to understand the problem.
